/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: vUv (https://sketchfab.com/vovaustimuk)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chair-b07d263a7ab942e6935e77cd75bf1194
Title: CHAIR
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Chair(props) {
  const { nodes, materials } = useGLTF("/chair.glb");
  return (
    <group scale={0.03} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 10]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.Material}
          position={[-1.877, -0.18, -8.205]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/chair.glb");