/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: MisterH (https://sketchfab.com/TGVMisterH)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/realistic-human-eye-f2370371544c4b029123da0b7d7e2457
Title: Realistic human eye
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Eye(props) {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF("/realistic_human_eye.glb");
    const { actions } = useAnimations(animations, group);
    useEffect(() => {
        if (props.talking) {
            actions.Animation.play()
        } else {
            actions.Animation.stop()
        }
    }, [props.talking])
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Sketchfab_Scene">
                <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
                    <group name="root">
                        <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
                            <group
                                name="Eye_Baked_2"
                                rotation={[Math.PI / 2, 0, 0]}
                                scale={2.383}
                            >
                                <mesh
                                    name="mesh_0"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.mesh_0.geometry}
                                    material={materials.Eye_Ball_Baked}
                                    morphTargetDictionary={nodes.mesh_0.morphTargetDictionary}
                                    morphTargetInfluences={nodes.mesh_0.morphTargetInfluences}
                                />
                            </group>
                            <group
                                name="Cornea_3"
                                rotation={[1.504, -0.011, 0.156]}
                                scale={2.412}
                            >
                                <mesh
                                    name="Object_6"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_6.geometry}
                                    material={materials.Cornea_Baked}
                                />
                            </group>
                        </group>
                    </group>
                </group>
            </group>
        </group>
    );
}

useGLTF.preload("/realistic_human_eye.glb");
