/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Wizard of Graphic (https://sketchfab.com/wizograph)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lightbulb-53f9dab8e41e4ebabb3ca78bc2a4d683
Title: Lightbulb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from 'three'

export function Lightbulb(props) {
  const { nodes, materials } = useGLTF("/lightbulb.glb");
//   console.log(nodes)
//   console.log(materials)
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group scale={0.15}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.ALL_LAMP_lamp_0.geometry}
            material={materials.lamp}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.ALL_LAMP_glass_0.geometry}
            material={props.on ? (new THREE.MeshStandardMaterial({
                emissive: new THREE.Color('#fffdd0'),
                emissiveIntensity: 1, // Adjust this value for desired intensity
            })) : materials.glass}
          />
          {/* <mesh castShadow receiveShadow scale={40} position={[0, 50, 0]}>
            <sphereGeometry />
            <meshStandardMaterial
                color="yellow"
                emissive="yellow"
                emissiveIntensity={100}
                opacity={0.01}
            />
          </mesh> */}
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/lightbulb.glb");