/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Jimmy Gunawan (https://sketchfab.com/jimmygunawan)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/blender-sushi-virtual-journal-16th-april-2020-634af2ae983f4fb8a9295e6b1b3d5c74
title: Blender Sushi Virtual Journal, 16th April 2020
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function TalkingHead(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/blender_sushi_virtual_journal_16th_april_2020.glb"
  );
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    if(props.talking){
        actions.Animation.play()
    }else{
        actions.Animation.stop()
    }
  }, [props.talking])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group
                name="grp_eyeLeft_1"
                position={[-0.03, 0.03, 0.03]}
                rotation={[0.09, 0, 0.04]}
                scale={0.01}
              >
                <group name="eyeLeft_0">
                  <mesh
                    name="Object_5"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_5.geometry}
                    material={materials.lambert5}
                  />
                </group>
              </group>
              <group
                name="grp_eyeRight_3"
                position={[0.04, 0.02, 0.02]}
                rotation={[0.09, 0, -0.02]}
                scale={0.01}
              >
                <group name="eyeRight_2">
                  <mesh
                    name="Object_8"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_8.geometry}
                    material={materials.lambert5}
                  />
                </group>
              </group>
              <group
                name="grp_transform_6"
                rotation={[0.03, -0.2, -0.02]}
                scale={0.01}
              >
                <group name="head_4">
                  <mesh
                    name="mesh_2"
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_2.geometry}
                    material={materials.lambert5}
                    morphTargetDictionary={nodes.mesh_2.morphTargetDictionary}
                    morphTargetInfluences={nodes.mesh_2.morphTargetInfluences}
                  />
                </group>
                <group name="teeth_5">
                  <mesh
                    name="Object_13"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_13.geometry}
                    material={materials.lambert5}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/blender_sushi_virtual_journal_16th_april_2020.glb");